# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('floor_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_study', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('lesson_type', models.CharField(choices=[('l', 'Лекція'), ('c', 'Консультація'), ('s', 'Семінар'), ('o', 'Інший'), ('b', 'Лабораторна')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('room_type', models.CharField(choices=[('s', 'семінарський'), ('l', 'лекційний'), ('a', 'адміністративний'), ('o', 'інший')], default='o', max_length=2)),
                ('id_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('id_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('mo', 'Понеділо'), ('tu', 'Вівторок'), ('we', 'Середа'), ('th', 'Четвер'), ('fr', "П'ятниця"), ('sa', 'Субота'), ('su', 'Неділя')], max_length=3)),
                ('week_type', models.CharField(choices=[('e', 'Парний тиждень'), ('n', 'Непарний тиждень'), ('b', 'І парний і непарний теждень')], max_length=2)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Group')),
                ('id_lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Lecturer')),
                ('id_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Lesson')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Room')),
                ('id_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.LessonTime')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='id_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Specialization'),
        ),
        migrations.AddField(
            model_name='group',
            name='id_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Specialization'),
        ),
    ]
