# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontime',
            name='time_begin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='time_end',
            field=models.TimeField(),
        ),
    ]
