# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170219_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('mo', 'Понеділок'), ('tu', 'Вівторок'), ('we', 'Середа'), ('th', 'Четвер'), ('fr', "П'ятниця"), ('sa', 'Субота'), ('su', 'Неділя')], max_length=3),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_type',
            field=models.CharField(choices=[('e', 'Парний тиждень'), ('n', 'Непарний тиждень'), ('b', 'Обоє тижні')], max_length=2),
        ),
    ]
