# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20170219_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота'), (7, 'Неділя')]),
        ),
    ]
