# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20170219_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('1', 'Понеділок'), ('2', 'Вівторок'), ('3', 'Середа'), ('4', 'Четвер'), ('5', "П'ятниця"), ('6', 'Субота'), ('7', 'Неділя')], max_length=2),
        ),
    ]
