# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20170220_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='week_type',
            field=models.CharField(choices=[('1', 'Парний тиждень'), ('2', 'Непарний тиждень'), ('0', 'Обоє тижні')], max_length=2),
        ),
    ]
