# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20170220_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_title', models.CharField(max_length=1024)),
                ('short_title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.Faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='university',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.University'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.University'),
            preserve_default=False,
        ),
    ]
