# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20170223_1037'),
    ]

    operations = [
		migrations.RenameField('Group', 'name', 'title')
    ]
