# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20170223_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontime',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_type',
            field=models.CharField(choices=[('1', 'Парний тиждень'), ('2', 'Непарний тиждень'), ('0', 'Ободви тижні')], max_length=2),
        ),
    ]
