# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20170223_1659'),
    ]

    operations = [
    ]
